# Generated by Django 5.2.6 on 2026-06-18 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("django_workflow_engine", "0007_add_enhanced_role_strategies"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_initial", models.BooleanField(default=False)),
                ("is_terminal", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("modified_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Model Status",
                "verbose_name_plural": "Model Statuses",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="ModelStatusConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "status_field",
                    models.CharField(
                        blank=True,
                        help_text="Optional target model field to sync with current status",
                        max_length=100,
                    ),
                ),
                ("auto_create_attachment", models.BooleanField(default=True)),
                (
                    "allow_direct_change",
                    models.BooleanField(
                        default=True,
                        help_text="Allow direct status changes when no workflow transition is used",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("modified_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Model Status Configuration",
                "verbose_name_plural": "Model Status Configurations",
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("modified_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "key",
                    models.SlugField(
                        blank=True,
                        help_text="Stable machine key for this status (e.g., in_progress)",
                        max_length=100,
                    ),
                ),
                ("name_en", models.CharField(help_text="English name", max_length=150)),
                (
                    "name_ar",
                    models.CharField(
                        blank=True, help_text="Arabic name", max_length=150
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("done", "Done"),
                            ("cancelled", "Cancelled"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Business category for reporting and behavior",
                        max_length=20,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Display color such as #2E74B5",
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Optional UI icon key", max_length=100
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extra flags or UI/business metadata for future use",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Status",
                "verbose_name_plural": "Statuses",
                "ordering": ("key", "id"),
            },
        ),
        migrations.CreateModel(
            name="StatusAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        help_text="The ID of the model instance", max_length=255
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("modified_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="StatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.CharField(max_length=255)),
                ("reason", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Status History",
                "verbose_name_plural": "Status History",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="StatusTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=100)),
                ("name_en", models.CharField(max_length=150)),
                ("name_ar", models.CharField(blank=True, max_length=150)),
                ("description", models.TextField(blank=True)),
                ("requires_approval", models.BooleanField(default=False)),
                ("approval_config", models.JSONField(blank=True, default=dict)),
                (
                    "reject_behavior",
                    models.CharField(
                        choices=[
                            ("stay_current_status", "Stay in Current Status"),
                            ("move_to_specific_status", "Move to Specific Status"),
                            ("request_changes", "Request Changes"),
                            ("cancel_workflow", "Cancel Workflow"),
                        ],
                        default="stay_current_status",
                        max_length=40,
                    ),
                ),
                (
                    "permission_codename",
                    models.CharField(
                        blank=True,
                        help_text="Optional permission codename required to perform transition",
                        max_length=150,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("modified_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Status Transition",
                "verbose_name_plural": "Status Transitions",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="WorkflowStatusNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_initial", models.BooleanField(default=False)),
                ("is_terminal", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("modified_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Workflow Status",
                "verbose_name_plural": "Workflow Statuses",
                "ordering": ("order", "id"),
            },
        ),
        migrations.RemoveConstraint(
            model_name="workflowaction",
            name="workflow_action_single_scope",
        ),
        migrations.AddField(
            model_name="workflowaction",
            name="condition_function",
            field=models.CharField(
                blank=True,
                help_text="Optional developer function that must return true before this action runs",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="workflowaction",
            name="failure_policy",
            field=models.CharField(
                choices=[
                    ("continue", "Continue"),
                    ("stop", "Stop Remaining Actions"),
                    ("raise", "Raise Error"),
                ],
                default="continue",
                help_text="Continue, stop remaining actions, or raise when execution fails",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="strategy",
            field=models.IntegerField(
                choices=[
                    (1, "Workflow → Pipeline → Stage - Approvals at stage level"),
                    (
                        2,
                        "Workflow → Pipeline - Approvals at pipeline level (no stages)",
                    ),
                    (
                        3,
                        "Workflow Only - Approvals at workflow level (no pipelines/stages)",
                    ),
                    (4, "Status Graph - Transitions between workflow statuses"),
                ],
                default=1,
                help_text="Workflow approval strategy: 1=Workflow only, 2=Workflow→Pipeline, 3=Workflow→Pipeline→Stage",
                verbose_name="Workflow Strategy",
            ),
        ),
        migrations.AlterField(
            model_name="workflowaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("after_approve", "After Approval"),
                    ("after_reject", "After Rejection"),
                    ("after_resubmission", "After Resubmission"),
                    ("after_delegate", "After Delegation"),
                    ("after_move_stage", "After Move Stage"),
                    ("after_move_pipeline", "After Move Pipeline"),
                    ("on_workflow_start", "On Workflow Start"),
                    ("on_workflow_complete", "On Workflow Complete"),
                    ("before_transition", "Before Status Transition"),
                    ("after_transition", "After Status Transition"),
                    (
                        "on_transition_approval_requested",
                        "On Transition Approval Requested",
                    ),
                    ("on_transition_approved", "On Transition Approved"),
                    ("on_transition_rejected", "On Transition Rejected"),
                    ("on_status_enter", "On Status Enter"),
                ],
                help_text="The type of action/event that triggers this action",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="modelstatus",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="model_statuses_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="modelstatus",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="model_statuses_modified",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="modelstatusconfiguration",
            name="content_type",
            field=models.OneToOneField(
                help_text="The model type that can use statuses",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_configuration",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="modelstatusconfiguration",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="model_status_configurations_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="modelstatusconfiguration",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="model_status_configurations_modified",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="modelstatus",
            name="configuration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="model_statuses",
                to="django_workflow_engine.modelstatusconfiguration",
            ),
        ),
        migrations.AddField(
            model_name="status",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Company/Organization user that owns this workflow",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_company",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="status",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional model type this status belongs to. Leave empty for global reusable statuses.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statuses",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="status",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="status",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_modified",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="modelstatusconfiguration",
            name="default_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_model_configurations",
                to="django_workflow_engine.status",
            ),
        ),
        migrations.AddField(
            model_name="modelstatus",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="model_statuses",
                to="django_workflow_engine.status",
            ),
        ),
        migrations.AddField(
            model_name="workflowattachment",
            name="current_status",
            field=models.ForeignKey(
                blank=True,
                help_text="Current business status controlled by status graph workflows",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workflow_attachments",
                to="django_workflow_engine.status",
            ),
        ),
        migrations.AddField(
            model_name="statusattachment",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="changed_status_attachments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="statusattachment",
            name="content_type",
            field=models.ForeignKey(
                help_text="The model type this status is attached to",
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="statusattachment",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="status_attachments",
                to="django_workflow_engine.status",
            ),
        ),
        migrations.AddField(
            model_name="statushistory",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="status_history_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="statushistory",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="statushistory",
            name="from_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="status_history_from",
                to="django_workflow_engine.status",
            ),
        ),
        migrations.AddField(
            model_name="statushistory",
            name="to_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="status_history_to",
                to="django_workflow_engine.status",
            ),
        ),
        migrations.AddField(
            model_name="statushistory",
            name="workflow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="status_history",
                to="django_workflow_engine.workflow",
            ),
        ),
        migrations.AddField(
            model_name="statustransition",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="status_transitions_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="statustransition",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="status_transitions_modified",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="statustransition",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_transitions",
                to="django_workflow_engine.workflow",
            ),
        ),
        migrations.AddField(
            model_name="statushistory",
            name="transition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="history_entries",
                to="django_workflow_engine.statustransition",
            ),
        ),
        migrations.AddField(
            model_name="workflowaction",
            name="transition",
            field=models.ForeignKey(
                blank=True,
                help_text="Status transition this action belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="django_workflow_engine.statustransition",
            ),
        ),
        migrations.AddField(
            model_name="workflowattachment",
            name="pending_transition",
            field=models.ForeignKey(
                blank=True,
                help_text="Transition waiting for approval",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pending_attachments",
                to="django_workflow_engine.statustransition",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowattachment",
            index=models.Index(
                fields=["current_status"], name="django_work_current_9ac160_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowattachment",
            index=models.Index(
                fields=["pending_transition"], name="django_work_pending_8f2260_idx"
            ),
        ),
        migrations.AddField(
            model_name="workflowstatusnode",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflow_status_nodes_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workflowstatusnode",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflow_status_nodes_modified",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workflowstatusnode",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workflow_nodes",
                to="django_workflow_engine.status",
            ),
        ),
        migrations.AddField(
            model_name="workflowstatusnode",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_nodes",
                to="django_workflow_engine.workflow",
            ),
        ),
        migrations.AddField(
            model_name="statustransition",
            name="from_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_transitions",
                to="django_workflow_engine.workflowstatusnode",
            ),
        ),
        migrations.AddField(
            model_name="statustransition",
            name="reject_to_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reject_transitions",
                to="django_workflow_engine.workflowstatusnode",
            ),
        ),
        migrations.AddField(
            model_name="statustransition",
            name="to_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_transitions",
                to="django_workflow_engine.workflowstatusnode",
            ),
        ),
        migrations.AddField(
            model_name="workflowaction",
            name="status_node",
            field=models.ForeignKey(
                blank=True,
                help_text="Workflow status node this action belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="django_workflow_engine.workflowstatusnode",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowaction",
            index=models.Index(
                fields=["transition", "action_type"],
                name="django_work_transit_0ecc94_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowaction",
            index=models.Index(
                fields=["status_node", "action_type"],
                name="django_work_status__e874d5_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("pipeline__isnull", True),
                        ("stage__isnull", True),
                        ("status_node__isnull", True),
                        ("transition__isnull", True),
                        ("workflow__isnull", False),
                    ),
                    models.Q(
                        ("pipeline__isnull", False),
                        ("stage__isnull", True),
                        ("status_node__isnull", True),
                        ("transition__isnull", True),
                        ("workflow__isnull", True),
                    ),
                    models.Q(
                        ("pipeline__isnull", True),
                        ("stage__isnull", False),
                        ("status_node__isnull", True),
                        ("transition__isnull", True),
                        ("workflow__isnull", True),
                    ),
                    models.Q(
                        ("pipeline__isnull", True),
                        ("stage__isnull", True),
                        ("status_node__isnull", True),
                        ("transition__isnull", False),
                        ("workflow__isnull", True),
                    ),
                    models.Q(
                        ("pipeline__isnull", True),
                        ("stage__isnull", True),
                        ("status_node__isnull", False),
                        ("transition__isnull", True),
                        ("workflow__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="workflow_action_single_scope",
            ),
        ),
        migrations.AddIndex(
            model_name="status",
            index=models.Index(fields=["key"], name="django_work_key_ffdd84_idx"),
        ),
        migrations.AddIndex(
            model_name="status",
            index=models.Index(
                fields=["content_type"], name="django_work_content_c2107e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="status",
            index=models.Index(
                fields=["category"], name="django_work_categor_be1c60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="status",
            index=models.Index(
                fields=["is_active"], name="django_work_is_acti_333f5f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="status",
            constraint=models.UniqueConstraint(
                fields=("company", "content_type", "key"),
                name="status_unique_company_content_type_key",
            ),
        ),
        migrations.AddIndex(
            model_name="modelstatus",
            index=models.Index(
                fields=["configuration", "is_active"],
                name="django_work_configu_873a51_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="modelstatus",
            index=models.Index(
                fields=["status"], name="django_work_status__6b8617_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="modelstatus",
            constraint=models.UniqueConstraint(
                fields=("configuration", "status"),
                name="model_status_unique_configuration_status",
            ),
        ),
        migrations.AddIndex(
            model_name="statusattachment",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="django_work_content_52fcf3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="statusattachment",
            index=models.Index(
                fields=["status"], name="django_work_status__a5822f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="statusattachment",
            unique_together={("content_type", "object_id")},
        ),
        migrations.AddIndex(
            model_name="statushistory",
            index=models.Index(
                fields=["content_type", "object_id", "created_at"],
                name="django_work_content_096290_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="statushistory",
            index=models.Index(
                fields=["workflow"], name="django_work_workflo_8e1713_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="statushistory",
            index=models.Index(
                fields=["transition"], name="django_work_transit_888392_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowstatusnode",
            index=models.Index(
                fields=["workflow", "is_active"], name="django_work_workflo_e7fed4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowstatusnode",
            index=models.Index(
                fields=["status"], name="django_work_status__9ed6c5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowstatusnode",
            constraint=models.UniqueConstraint(
                fields=("workflow", "status"),
                name="workflow_status_node_unique_workflow_status",
            ),
        ),
        migrations.AddIndex(
            model_name="statustransition",
            index=models.Index(
                fields=["workflow", "is_active"], name="django_work_workflo_bce1f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="statustransition",
            index=models.Index(
                fields=["from_status", "is_active"],
                name="django_work_from_st_89c17e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="statustransition",
            index=models.Index(
                fields=["to_status"], name="django_work_to_stat_99a199_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="statustransition",
            constraint=models.UniqueConstraint(
                fields=("workflow", "key"), name="status_transition_unique_workflow_key"
            ),
        ),
    ]
